# Local testing version of ELK stack designed for container-native
# deployment on Joyent's Triton platform.

kibana:
    extends:
      file: docker-compose.yml
      service: kibana
    mem_limit: 128m
    build: kibana/
    environment:
      - CONSUL=consul
    links:
    - consul:consul

logstash:
    extends:
      file: docker-compose.yml
      service: logstash
    mem_limit: 512m
    build: logstash/
    environment:
      - CONSUL=consul
    links:
    - consul:consul
    ports:
    - "514:514"             # syslog tcp port
    - "514/udp:514/udp"     # syslog udp port
    - "12201/udp:12201/udp" # gelf udp port
    # - "24224:24224"        # fluentd tcp port

elasticsearch_master:
    extends:
      file: docker-compose.yml
      service: elasticsearch
    image: es_elasticsearch
    mem_limit: 512m
    environment:
      - CONSUL=consul
      - ES_SERVICE_NAME=elasticsearch-master
      - ES_NODE_MASTER=true
      - ES_NODE_DATA=false
      - CONTAINERBUDDY=file:///etc/containerbuddy.json
    links:
    - consul:consul

elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch
    image: es_elasticsearch
    mem_limit: 512m
    environment:
      - CONSUL=consul
      - ES_SERVICE_NAME=elasticsearch-master
    links:
      - consul:consul

elasticsearch_data:
    extends:
      file: docker-compose.yml
      service: elasticsearch
    image: es_elasticsearch
    mem_limit: 512m
    environment:
      - CONSUL=consul
      - ES_SERVICE_NAME=elasticsearch-data
      - ES_NODE_MASTER=false
      - ES_NODE_DATA=true
    links:
      - consul:consul

consul:
    extends:
      file: docker-compose.yml
      service: consul
    ports:
      - 8500:8500
