# ---------------------------------------------------
# Nginx acts as our test source for logs to be ingested from the various
# log drivers.

# this is the base for our tests. override log_driver and log_opts
nginx:
    image: 0x74696d/triton-nginx
    mem_limit: 128m
    ports:
      - 80
    restart: always
    environment:
      - CONSUL
      - CONTAINERBUDDY
      - NGINX_CONF
    command: >
      /opt/containerbuddy/containerbuddy
      nginx -g "daemon off;"

nginx_syslog:
    extends:
      service: nginx
    mem_limit: 128m
    log_driver: syslog
    log_opt:
      syslog-address: "tcp://${LOGSTASH}"

nginx_gelf:
    extends:
      service: nginx
    mem_limit: 128m
    log_driver: gelf
    log_opt:
      gelf-address: "udp://${LOGSTASH}"

# Triton supports fluentd but logstash codec support is broken:
# https://github.com/logstash-plugins/logstash-codec-fluent/issues/2
# https://github.com/logstash-plugins/logstash-codec-fluent/pull/5

# nginx_fluentd:
#     extends:
#       service: nginx
#     mem_limit: 128m
#     log_driver: fluentd
#     log_opt:
#       fluentd-address: "${LOGSTASH}"
